apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appp
  name: appp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appp
    spec:
      containers:
        - image: 14066910/appp:v1
          name: appp
